spring:
  application:
    name: eureka-consumer

server:
  port: 33331

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.serviceUrl.eureka-server-port}/eureka/
